 es1=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.1.csv");
est=es1;
 est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.2.csv"); est = est + es1;
 est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.3.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.4.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.5.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.6.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.7.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.8.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.9.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.10.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.11.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.12.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.13.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.14.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.15.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.16.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.17.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.18.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.19.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.20.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.21.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.22.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.23.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.24.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.25.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.26.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.27.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.28.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.29.csv"); est = est + es1;
est=dlmread("C:\\projects\\neuralnet\\simplenet\\SNLogic\\es.30.csv"); est = est + es1;
est=est/30;
